version: "3"

services:
  docs:
    build:
      context: .
      dockerfile: ./apps/docs/Dockerfile
    restart: always
    ports:
      - "2000:3000"
    networks:
      - dokploy-network
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.docs.entrypoints=websecure"
     - "traefik.http.routers.docs.tls.certResolver=letsencrypt"
     - "traefik.http.routers.docs.rule=Host(`docs.postiva.app`)"
     - "traefik.http.services.docs.loadbalancer.server.port=2000"

networks:
  dokploy-network:
    external: true